# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #SRO CSRF protection is open now
    csrf_protection: true
    form:
        csrf_protection:
            enabled: true
    #         field_name: 'custom_token_name'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true
    
    #SRO http_method_override : true for use _method in form
    # permit symfony to recognize the request of HTTP like DELETE, PUT or all _method from form like POST => DELETE
    http_method_override: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
