twig:
    file_name_pattern: '*.twig'
    #SR use bootstrap_5_layout.html.twig for a nice form templates
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
