vich_uploader:
    db_driver: orm

    # mappings:
        #    products:
        #        uri_prefix: /images/products
        #        upload_destination: '%kernel.project_dir%/public/images/products'
        #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

# SRO : modify the way for thumbnails image : path and name
    mappings:
       Videos:
           uri_prefix: /Show_Page/Thumbnails
           upload_destination: '%kernel.project_dir%/public/Show_Page/Thumbnails'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           # namer can be different : https://github.com/dustin10/VichUploaderBundle/blob/master/docs/namers.md 
           # here the namer is SmartUniqueNamer : originalNameOfFile + strong uniqueid + originalExtensionOfFileName
        

            # MaxSize (default : 2M) and MimeTypes / AllowedMimeTypes( <= more restrictions) (default : all types) 
            # are treated on Video.php with Assert constraints
            # delete_on_update: false
            # delete_on_remove: default => true, should the file be deleted when the entity is deleted.
            # delete_on_update: default => true, should the file be deleted when a new file is uploaded.
            # inject_on_load: default => false, should the file be injected into the uploadable entity when loaded from the data store. 
            # The object will be an instance of Symfony\Component\HttpFoundation\File\File.

    